#+TITLE: 36-750 Course Documents

This repository contains design and practices checklists, the course rubric
and syllabus, and lecture notes for each class.

* Contact Info

  - Christopher Genovese, [[mailto:genovese@cmu.edu][genovese@cmu.edu]]
  - Alex Reinhart, [[mailto:areinhar@stat.cmu.edu][areinhar@stat.cmu.edu]]

  Please include [650] or [750] in the subject when you email us, so we can
  prioritize your email.

* Fall 2017 Office Hours Schedule

  | Day       |      Time | Person | Location |
  |-----------+-----------+--------+----------|
  | Monday    | 2:30-3:30 | Chris  | BH 232E  |
  | Tuesday   |       4-5 | Justin | BH 232K  |
  | Wednesday | 1:30-2:30 | Chris  | BH 232E  |
  | Wednesday | 2:30-3:30 | Alex   | BH 132Q  |
  | Thursday  |       3-4 | Chris  | BH 232E  |
  | Friday    | 2:30-3:30 | Alex   | BH 132A  |

  Note that on *Wednesday, September 6*, Chris's office hour will be at 3-4PM, not
  1:30-3:30, due to a schedule conflict.

  As always, if you can't make it to office hours or need extra help, don't
  hesitate to email us (with [650] or [750] in the subject line!) or ask for an
  appointment.
