#+TITLE: Version Control \\
#+TITLE: Statistics 650/750 \\
#+TITLE: Week 1 Thursday
#+DATE:  30 Aug 2018
#+AUTHOR: Alex Reinhart and Christopher Genovese

If you haven't already, do it *now*:

1. Register at https://github.com

2. Visit https://classroom.github.com/a/MMfm3qKz

3. Download and install Git: https://git-scm.com/

4. Accept the GitHub organization invitation you received (perhaps in the last
   hour!)


* Interlude: Setup Activity

  We will use these ideas and commands to set you up for the rest
  of the semester.

** Windows Pre-Setup

    First, *Windows users* running Git Bash need to run a script
    to set up their environment.

    To get the url, you can go to https://github.com/36-750
    Navigate to documents > ClassFiles > week1 > setup-profile.py
    And then hit the "Raw" button. Grab that URL and insert here.

    #+begin_src sh
      cd ~
      curl https://raw.githubusercontent.com/36-750/documents/master/ClassFiles/week1/setup-profile.py | python -
    #+end_src

    Then *exit and restart* Git Bash.

** Go Home

   Move to your home directory.  (How?)

   #+begin_src sh
     cd
   #+end_src

** Create a Class Directory and Move There

   Create directories =s750= and =bin= and
   switch to =s750=.

    #+begin_src sh
     mkdir s750 bin
     cd s750
   #+end_src

   The =bin= directory is where you will keep any
   utility scripts/programs that you want to use
   regularly.

   The =s750= directory is where you will keep
   all your work for this course throughout
   the semester.

** Setting Up Your Repositories

   When you have Git installed and have a GitHub
   account, do the following. Otherwise, you
   should do both steps before proceeding,
   as described in an email from Alex.

   If you try to do this later, remember to do it
   only *after* doing =cd ~/s750= first.

   1. Clone the course repositories

      #+begin_src sh
        git clone https://github.com/36-750/documents.git
        git clone https://github.com/36-750/problem-bank.git
      #+end_src

      You will probably need to use your GitHub username and password.

      If you get an error when you run the second command, you need to check
      your email for the GitHub invitation to join the 36-750 organization, and
      accept the invitation.

   2. Clone your assignment repository. If your github account
      name is =NNNN=, do

      #+begin_src sh
        git clone https://github.com/36-750/assignments-NNNN.git
      #+end_src

      replacing the NNNN with your account name in the command.

** Next Time

   When you want to work on your materials, start the shell,
   and return to your =s750= directory by typing

   #+begin_src sh
     cd ~/s750
   #+end_src
* Version Control

  #+INCLUDE: "../Topics/version-control.org"

* Extras                                                                                          :noexport:ARCHIVE:

#+OPTIONS: H:3 num:nil toc:nil
#+LATEX_HEADER: \usepackage{geometry}

# Local Variables:
# org-latex-packages-alist: (("" "tikz" t) ("" "tabu" nil) ("" "minted" nil))
# org-latex-minted-options:(("mathescape" "") ("linenos" "") ("numbersep" "5pt") ("gobble" "0") ("frame" "lines") ("framesep" "2mm"))
# org-latex-listings: minted
# org-latex-default-table-environment: tabu
# org-latex-create-formula-image-program: imagemagick
# org-latex-pdf-process: ("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f" "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f" "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f")
# org-image-actual-width: nil
# org-hide-emphasis-markers: t
# org-export-filter-strike-through-functions: (my/latex-strike-through-filter)
# End:
