#+TITLE: Getting updates to your assignments repository

We provided each of you with an assignments repository with some built-in
features, like the =new-homework= script and some setup to automatically run your
unit tests when you submit homework.

Unfortunately, some of this was broken. It would mistakenly report errors
whenever you submit homework, because if you wrote your homework in Python, it
would fail to find R unit tests, and if you wrote your homework in R, it would
fail to find Python unit tests.

I've fixed these problems, but it requires you to pull the changes I made into
your repository. Here's how.

** Step 1: Checkout master branch

   At your terminal, go to your =assignments-YOURUSERNAME= folder and switch to
   the master branch:

   #+BEGIN_SRC bash
     cd ~/s750/assignments-YOURUSERNAME

     git checkout master # Should be on the master branch
     git status
   #+END_SRC

   It should tell you "On branch master" and "nothing to commit".

   If it refuses to let you switch branch to master, you were probably working
   on something you haven't committed yet.

   If you have already submitted a homework assignment and had it approved, you
   should now run

   #+BEGIN_SRC bash
     git pull origin master
   #+END_SRC

   so that your =master= branch is updated with the merged homework.

** Step 2: Setup a new remote

   Now that you are on the master branch, we will add a new repository that we
   can pull changes from, including fixes to the bugs:

   #+BEGIN_SRC bash
     git remote add template https://github.com/36-750/assignment-template.git
     git remote -v
   #+END_SRC

   This should display a list that includes the lines

   #+BEGIN_EXAMPLE
     template	https://github.com/36-750/assignment-template.git (fetch)
     template	https://github.com/36-750/assignment-template.git (push)
   #+END_EXAMPLE

   If the above is displayed for you, then proceed to the next step.
   If not, please talk to us.

** Step 3: Pull down commits from the remote

   Now run the following command:

   #+BEGIN_SRC bash
     git pull template master
   #+END_SRC

  It will print out messages showing that it's updated several files, including
  =.drone.yml= and =.ci/run-tests.R=.

** Step 4: Done!

   You're now done.

   Note that GitHub will *not* allow you to push your =master= branch to GitHub. We
   don't allow this to ensure you don't accidentally commit homework directly to
   =master= without having it graded and approved first. (This has happened in the
   past.)

   This means that when you do your next homework assignment and submit it, the
   pull request on GitHub will show two extra commits -- the two commits I made
   to fix bugs. *That's fine!* Those will get merged into the =master= branch on
   GitHub when the TAs grade and approve your submission.
